### ISSUE TITLE
Feature Request: Need to collect logs under /CalicoWindows/logs in Windows nodes for AKS

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-diskinspect-service#175]
A new log folder `C:\CalicoWindows\logs` may exist in AKS Windows nodes when `calico` is used as network policy in AKS clusters with Windows agent pools. AKS needs to collect the logs in this folder. Request your help!

**Comment by AbelHu** [comment]
ping @chintanrp Could you help us? Thanks.

**Comment by mainred** [comment]
Maybe we can close this issue if the merged change is in production @chintanrp ?

**Comment by chintanrp** [comment]
yes, it's merged.
