### ISSUE TITLE
Q: Is it possible to run a script and then collect logs with disk-inspector?

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-diskinspect-service#191]
Is it possible to run a script and then collect logs with disk-inspector?
https://raw.githubusercontent.com/Microsoft/SDN/master/Kubernetes/windows/debug/collectlogs.ps1

**Comment by chintanrp** [comment]
@AbelHu  - That might be possible, but we do not allow any scripts to be run on customers' os disk. Specifically no write operation should be allowed.
If you want to do something similar you can check "repair vm" commands
