### ISSUE TITLE
Preserve File Create Time in Zip Archive

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-diskinspect-service#29]
When a file is copied to the zip archive the create time is when the file was copied out instead of the actual create time of the file.  The workaround is to call `ll` to get the create time, but it would be a lot better if the create time was preserved in .zip archive.

**Comment by jasonzio** [comment]
The zip file format doesn't have any mechanism to preserve file creation time. The file header (and corresponding central directory entry) can store only the last-modified time, and that can't store any time earlier than 1980-01-01.
