### ISSUE TITLE
Support Better Resolution on File Time Stamps

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-diskinspect-service#30]
Right now, the output of ll is the following.

```text
-rw-rw-r--   1 me me 27009 Mar  2 00:36 manifest_by_file.md
-rw-rw-r--   1 me me 66535 Mar  2 00:36 manifest_content.md
```

The timestamp has minute resolution, which isn't good enough to determine when a file was created.  There is a way to get better resolution on UNIX using `ls -al --time-style=full-iso`. Is it possible to do for azure-diskinspect-service.

```text
-rw-rw-r--   1 me me 27009 2018-03-02 00:36:25.519793900 +0000 manifest_by_file.md
-rw-rw-r--   1 me me 66535 2018-03-02 00:36:35.955793900 +0000 manifest_content.md
```

I don't see an exact implementation in libguestfs, but [guestfs_lstatnslist](http://libguestfs.org/guestfs.3.html#guestfs_lstatnslist) this may be a good start.

**Comment by amitchat** [comment]
Interesting to note that virt-ls actually lets you provide the ls parameters. Perhaps we need investigate if we can call into virt-ls instead of guestfish's ll to get the more advanced information.
